version: '2.2'

services:
  openhab:
    image: "openhab/openhab:4.0.4"
    container_name: openhab
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "openhab_addons:/openhab/addons"
      - "openhab_conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
    env_file:
      - default.env
    ports:
      - "8080:8080"
  influxdb:
    image: influxdb:2.7.4
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - "influxdb_storage:/var/lib/influxdb"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "mosquitto_config:/mosquitto/config:rw"
      - "mosquitto_data:/mosquitto/data:rw"
      - "mosquitto_log:/mosquitto/log:rw"

volumes:
  openhab_addons:
    driver: local
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local
  influxdb_storage:
    driver: local
  mosquitto_config:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local

networks:
 default:
  external:
    name: letsencrypt
